# -*- coding: utf-8 -*-
"""week3-A108260102-徐弘智.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1x-yqjMKsS-a3cFKqLmJ77Xj2f-jMhaKN
"""

print("Hello World")

print("我是徐弘智")